const { Unauthorized, NotFound } = require('http-errors')
const jwt = require('jsonwebtoken')
const { User } = require('../../models')

const { SECRET_KEY } = process.env

const authentication = async (req, res, next) => {
  try {
    const { authorization } = req.headers
    if (!authorization) throw new Unauthorized('No token')

    const [bearer, token] = authorization.split(' ')
    if (bearer !== 'Bearer') throw new Unauthorized('Not authorized')

    const { id } = jwt.verify(token, SECRET_KEY)

    const userData = await User.findById(id)

    if (!userData) throw new NotFound(`Can't find user with id ${id}`)
    if (token !== userData.token) throw new Unauthorized('Wrong token')

    req.user = userData

    next()
  } catch (error) {
    // Add status to error generated by jwt.verify
    if (!error.status) error.status = 401
    next(error)
  }
}

module.exports = authentication
